name: Pull Request
on: [pull_request]
jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Format check
        run: yarn ci:format
  Site_Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Test examples and hrefs
        run: yarn test
  Vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build ReScript
        run: yarn build:res
      - name: Install Playwright
        run: yarn playwright install --with-deps
      - name: Vitest
        run: yarn ci:test
